version: "3.8"

services:

    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        #MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=eventsProjectdb
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql
    
    prometheus:
      image: prom/prometheus
      container_name: prometheus-eventsProject-backend
      restart: unless-stopped
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      links:
        - prom_mysql_exporter
      ports:
        - 9090:9090

    prom_mysql_exporter:
      image: prom/mysqld-exporter
      restart: unless-stopped
      links:
        - mysqldb
      ports:
        - '9104:9104'
      environment:
        DATA_SOURCE_NAME: root:@(mysql:3306)/eventsProjectdb
      command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true

    grafana:
        image: grafana/grafana
        container_name: grafana-eventsProject-backend
        restart: unless-stopped
        ports:
          - 3000:3000
        volumes:
          - ./grafana:/etc/grafana/provisioning
          - ./grafana/dashboards:/var/lib/grafana/dashboards
          - ./grafana/datasources:/var/lib/grafana/datasources
        environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=thinkpad


    eventsProject-backend:
        depends_on:
          - mysqldb
        image: korma666/eventsProject:1.0.0
        restart: on-failure
        ports:
          - 8082:8082
        environment:
          SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/eventsProjectdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
        }'

        stdin_open: true
        tty: true
volumes:
    db:
    prometheus_data:
